apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: x7ei79rvy-dotnet-basic-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/x7ei79rvy-dotnet-basic